export const jogos = [
  // JOGOS DE TERÇA-FEIRA 25/11/2025 - QUADRA: GINÁSIO DE ESPORTES
  {
    data: "2025-11-25",
    hora: "17:00",
    jogo: "CEBN X CONVENIADA",
    modalidade: "Handebol Feminino Sub 15",
    ordem: "jogo 1",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-25",
    hora: "17:50",
    jogo: "CEJA X CEBC",
    modalidade: "Handebol Masculino Sub 17",
    ordem: "jogo 2",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-25",
    hora: "18:40",
    jogo: "CEBC X CETI",
    modalidade: "Futsal Feminino Sub 17",
    ordem: "jogo 3",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-25",
    hora: "19:30",
    jogo: "CEBC X CETI",
    modalidade: "Futsal Masculino Sub 17",
    ordem: "jogo 4",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-25",
    hora: "20:20",
    jogo: "LUCIA ROCHA X VITORIA LIMA",
    modalidade: "Futsal Feminino Aberto",
    ordem: "jogo 5",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-25",
    hora: "21:00",
    jogo: "CEBC X CETI",
    modalidade: "Futsal Masculino Aberto",
    ordem: "jogo 6",
    local: "Ginásio de Esportes",
  },

  // JOGOS DE QUARTA FEIRA 26/11/2025 - QUADRA: GINÁSIO DE ESPORTES
  {
    data: "2025-11-26",
    hora: "08:00",
    jogo: "JOSÉ DIAS X MARIA DA GLORIA",
    modalidade: "Futsal Masculino Sub 11",
    ordem: "jogo 7",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-26",
    hora: "08:40",
    jogo: "CONVENIADA X CEJA",
    modalidade: "Futsal Feminino Sub 13",
    ordem: "jogo 8",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-26",
    hora: "09:20",
    jogo: "CONVENIADA X CEBC",
    modalidade: "Futsal Masculino Sub 13",
    ordem: "jogo 9",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-26",
    hora: "10:00",
    jogo: "CEJA X PORTAL DO SABER",
    modalidade: "Futsal Masculino Sub 11",
    ordem: "jogo 10",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-26",
    hora: "10:40",
    jogo: "CETI X CEJA",
    modalidade: "Baleado Masculino Sub 17",
    ordem: "jogo 11",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-26",
    hora: "11:20",
    jogo: "ADELIETA RAMALHO X JOSÉ DIAS",
    modalidade: "Futsal Masculino Sub 7",
    ordem: "jogo 12",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-26",
    hora: "12:00",
    jogo: "CEJA X CEBC",
    modalidade: "Basquete Feminino Sub 15",
    ordem: "jogo 13",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-26",
    hora: "12:40",
    jogo: "CEBC X CEJA",
    modalidade: "Basquete Masculino Sub 13",
    ordem: "jogo 14",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-26",
    hora: "13:20",
    jogo: "CETI X CEBC",
    modalidade: "Basquete Masculino Sub 17",
    ordem: "jogo 15",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-26",
    hora: "14:00",
    jogo: "CETI X LUCIA ROCHA",
    modalidade: "Volei Aberto Feminino",
    ordem: "jogo 16",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-26",
    hora: "14:40",
    jogo: "LUCIA ROCHA X CETI",
    modalidade: "Volei Aberto Masculino",
    ordem: "jogo 17",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-26",
    hora: "15:20",
    jogo: "ADELIETA RAMALHO X CEJA",
    modalidade: "Handebol Masculino Sub 11",
    ordem: "jogo 18",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-26",
    hora: "16:00",
    jogo: "MARIA DA GLORIA X FRANCISCO AMORIM",
    modalidade: "Handebol Feminino Sub 11",
    ordem: "jogo 19",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-26",
    hora: "16:40",
    jogo: "CEJA X JOSÉ DIAS",
    modalidade: "Futsal Feminino Sub 15",
    ordem: "jogo 20",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-26",
    hora: "17:20",
    jogo: "MANOEL RAMOS X JOSÉ DIAS",
    modalidade: "Futsal Masculino Sub 15",
    ordem: "jogo 21",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-26",
    hora: "18:00",
    jogo: "CEJA X VITORIA LIMA",
    modalidade: "Futsal Masculino Sub 17",
    ordem: "jogo 22",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-26",
    hora: "18:40",
    jogo: "CEJA X VITORIA LIMA",
    modalidade: "Futsal Feminino Sub 17",
    ordem: "jogo 23",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-26",
    hora: "19:20",
    jogo: "LUCIA ROCHA X VITORIA LIMA",
    modalidade: "Futsal Masculino Aberto",
    ordem: "jogo 24",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-26",
    hora: "20:00",
    jogo: "CEBC X CETI",
    modalidade: "Futsal Feminino Aberto",
    ordem: "jogo 25",
    local: "Ginásio de Esportes",
  },

  // JOGOS DE QUARTA FEIRA 26/11/2025 - QUADRA: ADELIETA RAMALHO
  {
    data: "2025-11-26",
    hora: "08:00",
    jogo: "MANOEL RAMOS X PORTAL DO SABER",
    modalidade: "Baleado Feminino Sub 11",
    ordem: "jogo 26",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-26",
    hora: "09:20",
    jogo: "JOSÉ DIAS X MANOEL RAMOS",
    modalidade: "Baleado Feminino Sub 11",
    ordem: "jogo 27",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-26",
    hora: "10:00",
    jogo: "MANOEL RAMOS X ADELIETA RAMALHO",
    modalidade: "Baleado Masculino Sub 11",
    ordem: "jogo 28",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-26",
    hora: "11:20",
    jogo: "ADELIETA RAMALHO X JOSÉ DIAS",
    modalidade: "Baleado Masculino Sub 13",
    ordem: "jogo 29",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-26",
    hora: "11:30",
    jogo: "MANOEL RAMOS X PORTAL DO SABER",
    modalidade: "Baleado Feminino Sub 11",
    ordem: "jogo 30",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-26",
    hora: "14:00",
    jogo: "FRANCISCO AMORIM X CEJA",
    modalidade: "Futsal Masculino Sub 11",
    ordem: "jogo 31",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-26",
    hora: "14:40",
    jogo: "JOSÉ DIAS X MARLENE SANTANA",
    modalidade: "Futsal Feminino Sub 11",
    ordem: "jogo 32",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-26",
    hora: "15:20",
    jogo: "EMILIANO ZAPATA X JOSÉ DIAS",
    modalidade: "Futsal Masculino Sub 11",
    ordem: "jogo 33",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-26",
    hora: "16:00",
    jogo: "ADELIETA RAMALHO X CEBC",
    modalidade: "Futsal Masculino Sub 11",
    ordem: "jogo 34",
    local: "Adelieta Ramalho",
  },

  // JOGOS DE QUARTA FEIRA 26/11/2025 - QUADRA: MARIA DA GLÓRIA
  {
    data: "2025-11-26",
    hora: "08:00",
    jogo: "CEJA X CEBC",
    modalidade: "Baleado Masculino Sub 13",
    ordem: "jogo 35",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-26",
    hora: "08:40",
    jogo: "JOSÉ DIAS X MANOEL RAMOS",
    modalidade: "Baleado Masculino Sub 13",
    ordem: "jogo 36",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-26",
    hora: "09:20",
    jogo: "MARIA DA GLORIA X FRANCISCO AMORIM",
    modalidade: "Baleado Masculino Sub 11",
    ordem: "jogo 37",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-26",
    hora: "12:40",
    jogo: "JOSÉ DIAS X PORTAL DO SABER",
    modalidade: "Futsal Masculino Sub 8",
    ordem: "jogo 38",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-26",
    hora: "13:20",
    jogo: "CEJA X CONVENIADA",
    modalidade: "Handebol Feminino Sub 13",
    ordem: "jogo 39",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-26",
    hora: "14:00",
    jogo: "CONVENIADA X CEJA",
    modalidade: "Handebol Masculino Sub 13",
    ordem: "jogo 40",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-26",
    hora: "14:40",
    jogo: "CEBN X CEJA",
    modalidade: "Futsal Feminino Sub 13",
    ordem: "jogo 41",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-26",
    hora: "15:20",
    jogo: "JOSÉ DIAS X CONVENIADA",
    modalidade: "Futsal Masculino Sub 13",
    ordem: "jogo 42",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-26",
    hora: "16:00",
    jogo: "CEBC X FRANCISCO AMORIM",
    modalidade: "Futsal Masculino Sub 13",
    ordem: "jogo 43",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-26",
    hora: "16:40",
    jogo: "JOSÉ DIAS X CONVENIADA",
    modalidade: "Futsal Feminino Sub 13",
    ordem: "jogo 44",
    local: "Maria da Glória",
  },

  // JOGOS DE QUARTA FEIRA 26/11/2025 - QUADRA: C E J A
  {
    data: "2025-11-26",
    hora: "08:00",
    jogo: "CEJA X EMILIANO ZAPATA",
    modalidade: "Volei Masculino Sub 15",
    ordem: "jogo 45",
    local: "CEJA",
  },
  {
    data: "2025-11-26",
    hora: "08:40",
    jogo: "EMILIANO ZAPATA X CEJA",
    modalidade: "Volei Feminino Sub 15",
    ordem: "jogo 46",
    local: "CEJA",
  },
  {
    data: "2025-11-26",
    hora: "09:20",
    jogo: "LUCIA ROCHA X CEBC",
    modalidade: "Volei Masculino Sub 17",
    ordem: "jogo 47",
    local: "CEJA",
  },
  {
    data: "2025-11-26",
    hora: "10:00",
    jogo: "CETI X VITORIA LIMA",
    modalidade: "Volei Feminino Sub 17",
    ordem: "jogo 48",
    local: "CEJA",
  },
  {
    data: "2025-11-26",
    hora: "10:40",
    jogo: "CETI X CEBN",
    modalidade: "Volei Sub 17 Masculino",
    ordem: "jogo 49",
    local: "CEJA",
  },
  {
    data: "2025-11-26",
    hora: "11:20",
    jogo: "CONVENIADA X JOSÉ DIAS",
    modalidade: "Handebol Masculino Sub 15",
    ordem: "jogo 50",
    local: "CEJA",
  },
  {
    data: "2025-11-26",
    hora: "12:00",
    jogo: "CONVENIADA X CEBN",
    modalidade: "Handebol Feminino Sub 15",
    ordem: "jogo 51",
    local: "CEJA",
  },
  {
    data: "2025-11-26",
    hora: "12:40",
    jogo: "CEJA X CETI",
    modalidade: "Handebol Masculino Sub 17",
    ordem: "jogo 52",
    local: "CEJA",
  },
  {
    data: "2025-11-26",
    hora: "13:20",
    jogo: "CEJA X CEBC",
    modalidade: "Handebol Masculino Sub 15",
    ordem: "jogo 53",
    local: "CEJA",
  },
  {
    data: "2025-11-26",
    hora: "14:00",
    jogo: "JOSÉ DIAS X CEJA",
    modalidade: "Handebol Feminino Sub 15",
    ordem: "jogo 54",
    local: "CEJA",
  },
  {
    data: "2025-11-26",
    hora: "14:40",
    jogo: "CEJA X CONVENIADA",
    modalidade: "Baleado Masculino Sub 13",
    ordem: "jogo 55",
    local: "CEJA",
  },
  {
    data: "2025-11-26",
    hora: "15:20",
    jogo: "CETI X CEJA",
    modalidade: "Baleado Feminino Sub 17",
    ordem: "jogo 56",
    local: "CEJA",
  },
  {
    data: "2025-11-26",
    hora: "16:00",
    jogo: "CONVENIADA X CEBC",
    modalidade: "Baleado Feminino Sub 15",
    ordem: "jogo 57",
    local: "CEJA",
  },

  // JOGOS DE QUARTA FEIRA 26/11/2025 - QUADRA: CETI
  {
    data: "2025-11-26",
    hora: "08:00",
    jogo: "ADELIETA RAMALHO X FRANCISCO AMORIM",
    modalidade: "Futsal Masculino Sub 8",
    ordem: "jogo 58",
    local: "CETI",
  },
  {
    data: "2025-11-26",
    hora: "08:40",
    jogo: "JOSÉ DIAS X FRANCISCO AMORIM",
    modalidade: "Futsal Masculino Sub 9",
    ordem: "jogo 59",
    local: "CETI",
  },
  {
    data: "2025-11-26",
    hora: "09:20",
    jogo: "TEODULO LEITE X PORTAL DO SABER",
    modalidade: "Futsal Masculino Sub 7",
    ordem: "jogo 60",
    local: "CETI",
  },
  {
    data: "2025-11-26",
    hora: "10:00",
    jogo: "ACM X FRANCISCO AMORIM",
    modalidade: "Baleado Masculino Sub 8",
    ordem: "jogo 61",
    local: "CETI",
  },
  {
    data: "2025-11-26",
    hora: "10:40",
    jogo: "TEODULO LEITE X ADELIETA RAMALHO",
    modalidade: "Baleado Masculino Sub 8",
    ordem: "jogo 62",
    local: "CETI",
  },
  {
    data: "2025-11-26",
    hora: "12:00",
    jogo: "PORTAL DO SABER X ADELIETA RAMALHO",
    modalidade: "Baleado Feminino Sub 9",
    ordem: "jogo 63",
    local: "CETI",
  },
  {
    data: "2025-11-26",
    hora: "14:00",
    jogo: "MARIA DA GLORIA X FRANCISCO AMORIM",
    modalidade: "Baleado Feminino Sub 9",
    ordem: "jogo 64",
    local: "CETI",
  },
  {
    data: "2025-11-26",
    hora: "14:40",
    jogo: "PORTAL DO SABER X ACM",
    modalidade: "Baleado Feminino Sub 8",
    ordem: "jogo 65",
    local: "CETI",
  },
  {
    data: "2025-11-26",
    hora: "15:20",
    jogo: "ACM X FRANCISCO AMORIM",
    modalidade: "Handebol Masculino Sub 9",
    ordem: "jogo 66",
    local: "CETI",
  },
  {
    data: "2025-11-26",
    hora: "16:00",
    jogo: "ACM X MARLENE SANTANA",
    modalidade: "Handebol Feminino Sub 9",
    ordem: "jogo 67",
    local: "CETI",
  },

  // JOGOS DE QUARTA FEIRA 26/11/2025 - QUADRA: CEBN
  {
    data: "2025-11-26",
    hora: "09:20",
    jogo: "ADELIETA RAMALHO X MARLENE SANTANA",
    modalidade: "Handebol Masculino Sub 11",
    ordem: "jogo 68",
    local: "CEBN",
  },
  {
    data: "2025-11-26",
    hora: "10:00",
    jogo: "MARLENE SANTANA X ADELIETA RAMALHO",
    modalidade: "Handebol Feminino Sub 9",
    ordem: "jogo 69",
    local: "CEBN",
  },
  {
    data: "2025-11-26",
    hora: "10:40",
    jogo: "FRANCISCO AMORIM X MARLENE SANTANA",
    modalidade: "Futsal Masculino Sub 9",
    ordem: "jogo 70",
    local: "CEBN",
  },
  {
    data: "2025-11-26",
    hora: "11:20",
    jogo: "FRANCISCO AMORIM X MARLENE SANTANA",
    modalidade: "Handebol Feminino Sub 11",
    ordem: "jogo 71",
    local: "CEBN",
  },
  {
    data: "2025-11-26",
    hora: "12:00",
    jogo: "CEBN X CONVENIADA",
    modalidade: "Baleado Feminino Sub 13",
    ordem: "jogo 72",
    local: "CEBN",
  },
  {
    data: "2025-11-26",
    hora: "12:40",
    jogo: "CEBN X CONVENIADA",
    modalidade: "Baleado Masculino Sub 15",
    ordem: "jogo 73",
    local: "CEBN",
  },
  {
    data: "2025-11-26",
    hora: "13:20",
    jogo: "CEBC X CEBN",
    modalidade: "Baleado Masculino Sub 13",
    ordem: "jogo 74",
    local: "CEBN",
  },
  {
    data: "2025-11-26",
    hora: "14:00",
    jogo: "CEBN X CEBC",
    modalidade: "Handebol Masculino Sub 13",
    ordem: "jogo 75",
    local: "CEBN",
  },
  {
    data: "2025-11-26",
    hora: "14:40",
    jogo: "CEJA X CEBN",
    modalidade: "Futsal Masculino Sub 13",
    ordem: "jogo 76",
    local: "CEBN",
  },
  {
    data: "2025-11-26",
    hora: "15:20",
    jogo: "CEBN X CEBC",
    modalidade: "Futsal Masculino Sub 15",
    ordem: "jogo 77",
    local: "CEBN",
  },

  // JOGOS DE QUARTA FEIRA 26/11/2025 - QUADRA: JOSENILDO LEITE
  {
    data: "2025-11-26",
    hora: "08:40",
    jogo: "CEBC X JOSENILDO LEITE",
    modalidade: "Futsal Feminino Sub 15",
    ordem: "jogo 78",
    local: "Josenildo Leite",
  },
  {
    data: "2025-11-26",
    hora: "10:40",
    jogo: "JOSENILDO LEITE X EMILIANO ZAPATA",
    modalidade: "Futsal Masculino Sub 13",
    ordem: "jogo 79",
    local: "Josenildo Leite",
  },
  {
    data: "2025-11-26",
    hora: "13:20",
    jogo: "JOSENILDO LEITE X MANOEL RAMOS",
    modalidade: "Futsal Masculino Sub 15",
    ordem: "jogo 80",
    local: "Josenildo Leite",
  },
  {
    data: "2025-11-26",
    hora: "14:00",
    jogo: "CONVENIADA X JOSENILDO LEITE",
    modalidade: "Futsal Masculino Sub 11",
    ordem: "jogo 81",
    local: "Josenildo Leite",
  },

  // JOGOS DE QUINTA FEIRA 27/11/2025 - QUADRA: GINÁSIO DE ESPORTES
  {
    data: "2025-11-27",
    hora: "08:00",
    jogo: "CEBC X CETI",
    modalidade: "Volei Sub 17 Masculino",
    ordem: "jogo 82",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-27",
    hora: "08:40",
    jogo: "VITORIA LIMA X CETI",
    modalidade: "Volei Misto Aberto",
    ordem: "jogo 83",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-27",
    hora: "09:20",
    jogo: "CEBC X LUCIA ROCHA",
    modalidade: "Volei Misto Aberto",
    ordem: "jogo 84",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-27",
    hora: "10:00",
    jogo: "VITORIA LIMA X CEBC",
    modalidade: "Futsal Feminino Sub 17",
    ordem: "jogo 85",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-27",
    hora: "10:40",
    jogo: "TEODULO LEITE X ACM",
    modalidade: "Futsal Masculino Sub 7",
    ordem: "jogo 86",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-27",
    hora: "11:20",
    jogo: "TEODULO LEITE X PORTAL DO SABER",
    modalidade: "Futsal Masculino Sub 8",
    ordem: "jogo 87",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-27",
    hora: "12:00",
    jogo: "EMILIANO ZAPATA X ADELIETA RAMALHO",
    modalidade: "Futsal Masculino Sub 9",
    ordem: "jogo 88",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-27",
    hora: "12:40",
    jogo: "CEBC X CETI",
    modalidade: "Basquete Feminino Sub 17",
    ordem: "jogo 89",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-27",
    hora: "13:20",
    jogo: "CEBC X CEJA",
    modalidade: "Basquete Masculino Sub 17",
    ordem: "jogo 90",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-27",
    hora: "14:00",
    jogo: "MARIA DA GLORIA X FRANCISCO AMORIM",
    modalidade: "Baleado Masculino Sub 11",
    ordem: "jogo 91",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-27",
    hora: "14:40",
    jogo: "MARIA DA GLORIA X JOSENILDO LEITE",
    modalidade: "Baleado Feminino Sub 11",
    ordem: "jogo 92",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-27",
    hora: "15:20",
    jogo: "CEBC X CONVENIADA",
    modalidade: "Handebol Masculino Sub 15",
    ordem: "jogo 93",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-27",
    hora: "16:00",
    jogo: "CETI X CEBC",
    modalidade: "Handebol Masculino Sub 17",
    ordem: "jogo 94",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-27",
    hora: "16:40",
    jogo: "LUCIA ROCHA X CETI",
    modalidade: "Handebol Feminino Aberto",
    ordem: "jogo 95",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-27",
    hora: "17:20",
    jogo: "VITORIA LIMA X CETI",
    modalidade: "Futsal Feminino Aberto",
    ordem: "jogo 96",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-27",
    hora: "18:00",
    jogo: "CETI X CEJA",
    modalidade: "Futsal Feminino Sub 17",
    ordem: "jogo 97",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-27",
    hora: "18:40",
    jogo: "CEBC X LUCIA ROCHA",
    modalidade: "Futsal Feminino Aberto",
    ordem: "jogo 98",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-27",
    hora: "19:20",
    jogo: "MANOEL RAMOS X LUCIA ROCHA",
    modalidade: "Futsal Masculino Aberto",
    ordem: "jogo 99",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-27",
    hora: "20:00",
    jogo: "JOSENILDO LEITE X CEJA",
    modalidade: "Futsal Masculino Sub 17",
    ordem: "jogo 100",
    local: "Ginásio de Esportes",
  },

  // JOGOS DE QUINTA FEIRA 27/11/2025 - QUADRA: ADELIETA RAMALHO
  {
    data: "2025-11-27",
    hora: "08:00",
    jogo: "PORTAL DO SABER X FRANCISCO AMORIM",
    modalidade: "Futsal Masculino Sub 11",
    ordem: "jogo 101",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-27",
    hora: "08:40",
    jogo: "MARLENE SANTANA X CONVENIADA",
    modalidade: "Futsal Masculino Sub 11",
    ordem: "jogo 102",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-27",
    hora: "09:20",
    jogo: "CEBC X ADELIETA",
    modalidade: "Futsal Masculino Sub 11",
    ordem: "jogo 103",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-27",
    hora: "10:00",
    jogo: "MARIA DA GLORIA X FRANCISCO AMORIM",
    modalidade: "Baleado Feminino Sub 11",
    ordem: "jogo 104",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-27",
    hora: "10:40",
    jogo: "ADELIETA RAMALHO X FRANCISCO AMORIM",
    modalidade: "Baleado Feminino Sub 9",
    ordem: "jogo 105",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-27",
    hora: "11:20",
    jogo: "MARLENE SANTANA X CEJA",
    modalidade: "Handebol Masculino Sub 11",
    ordem: "jogo 106",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-27",
    hora: "12:00",
    jogo: "CONVENIADA X CEJA",
    modalidade: "Baleado Feminino Sub 13",
    ordem: "jogo 107",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-27",
    hora: "12:40",
    jogo: "ADELIETA RAMALHO X FRANCISCO AMORIM",
    modalidade: "Handebol Feminino Sub 11",
    ordem: "jogo 108",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-27",
    hora: "13:20",
    jogo: "MARLENE SANTANA X MARIA DA GLORIA",
    modalidade: "Handebol Feminino Sub 11",
    ordem: "jogo 109",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-27",
    hora: "14:00",
    jogo: "EMILIANO ZAPATA X JOSENILDO LEITE",
    modalidade: "Volei Masculino Sub 15",
    ordem: "jogo 110",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-27",
    hora: "14:40",
    jogo: "CEBC X VITORIA LIMA",
    modalidade: "Volei Misto Aberto",
    ordem: "jogo 111",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-27",
    hora: "15:20",
    jogo: "CETI X LUCIA ROCHA",
    modalidade: "Volei Masculino Sub 17",
    ordem: "jogo 112",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-27",
    hora: "16:00",
    jogo: "CEBC X CEBN",
    modalidade: "Volei Masculino Sub 17",
    ordem: "jogo 113",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-27",
    hora: "16:40",
    jogo: "LUCIA ROCHA X CETI",
    modalidade: "Volei Misto Aberto",
    ordem: "jogo 114",
    local: "Adelieta Ramalho",
  },

  // JOGOS DE QUINTA FEIRA 27/11/2025 - QUADRA: MARIA DA GLÓRIA
  {
    data: "2025-11-27",
    hora: "08:00",
    jogo: "CEJA X CEBC",
    modalidade: "Baleado Masculino Sub 15",
    ordem: "jogo 115",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-27",
    hora: "08:40",
    jogo: "CEBN X CEBC",
    modalidade: "Baleado Feminino Sub 15",
    ordem: "jogo 116",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-27",
    hora: "09:20",
    jogo: "CEJA X CONVENIADA",
    modalidade: "Baleado Feminino Sub 15",
    ordem: "jogo 117",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-27",
    hora: "10:00",
    jogo: "CEBC X CONVENIADA",
    modalidade: "Handebol Masculino Sub 13",
    ordem: "jogo 118",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-27",
    hora: "10:40",
    jogo: "CEJA X CEBN",
    modalidade: "Handebol Masculino Sub 13",
    ordem: "jogo 119",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-27",
    hora: "11:20",
    jogo: "CONVENIADA X CEBC",
    modalidade: "Handebol Feminino Sub 13",
    ordem: "jogo 120",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-27",
    hora: "12:00",
    jogo: "ADELIETA RAMALHO X JOSENILDO LEITE",
    modalidade: "Baleado Feminino Sub 11",
    ordem: "jogo 121",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-27",
    hora: "12:40",
    jogo: "CONVENIADA X CEBN",
    modalidade: "Baleado Feminino Sub 13",
    ordem: "jogo 122",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-27",
    hora: "13:00",
    jogo: "PORTAL DO SABER X MARIA DA GLORIA",
    modalidade: "Baleado Feminino Sub 9",
    ordem: "jogo S/N",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-27",
    hora: "13:20",
    jogo: "MARIA DA GLORIA X EMILIANO ZAPATA",
    modalidade: "Futsal Masculino Sub 11",
    ordem: "jogo 123",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-27",
    hora: "14:00",
    jogo: "MARLENE SANTANA X JOSE DIAS",
    modalidade: "Futsal Masculino Sub 8",
    ordem: "jogo 124",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-27",
    hora: "14:40",
    jogo: "CEJA X JOSENILDO LEITE",
    modalidade: "Futsal Masculino Sub 13",
    ordem: "jogo 125",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-27",
    hora: "15:20",
    jogo: "CEBN X JOSE DIAS",
    modalidade: "Futsal Feminino Sub 13",
    ordem: "jogo 126",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-27",
    hora: "16:00",
    jogo: "EMILIANO ZAPATA X CEBN",
    modalidade: "Futsal Masculino Sub 13",
    ordem: "jogo 127",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-27",
    hora: "16:40",
    jogo: "FRANCISCO AMORIM X JOSE DIAS",
    modalidade: "Futsal Masculino Sub 13",
    ordem: "jogo 128",
    local: "Maria da Glória",
  },

  // JOGOS DE QUINTA FEIRA 27/11/2025 - QUADRA: C E J A
  {
    data: "2025-11-27",
    hora: "08:00",
    jogo: "CEJA X CETI",
    modalidade: "Handebol Feminino Sub 17",
    ordem: "jogo 129",
    local: "CEJA",
  },
  {
    data: "2025-11-27",
    hora: "08:40",
    jogo: "JOSÉ DIAS X CEBC",
    modalidade: "Handebol Feminino Sub 15",
    ordem: "jogo 130",
    local: "CEJA",
  },
  {
    data: "2025-11-27",
    hora: "09:20",
    jogo: "CONVENIADA X CEJA",
    modalidade: "Handebol Masculino Sub 15",
    ordem: "jogo 131",
    local: "CEJA",
  },
  {
    data: "2025-11-27",
    hora: "10:00",
    jogo: "CEBC X JOSE DIAS",
    modalidade: "Handebol Masculino Sub 15",
    ordem: "jogo 132",
    local: "CEJA",
  },
  {
    data: "2025-11-27",
    hora: "10:40",
    jogo: "CEJA X MANOEL RAMOS",
    modalidade: "Futsal Masculino Sub 15",
    ordem: "jogo 133",
    local: "CEJA",
  },
  {
    data: "2025-11-27",
    hora: "11:20",
    jogo: "JOSENILDO LEITE X EMILIANO ZAPATA",
    modalidade: "Futsal Feminino Sub 15",
    ordem: "jogo 134",
    local: "CEJA",
  },
  {
    data: "2025-11-27",
    hora: "12:00",
    jogo: "CONVENIADA X EMILIANO ZAPATA",
    modalidade: "Futsal Masculino Sub 15",
    ordem: "jogo 135",
    local: "CEJA",
  },
  {
    data: "2025-11-27",
    hora: "12:40",
    jogo: "CEBN X CEJA",
    modalidade: "Futsal Feminino Sub 15",
    ordem: "jogo 136",
    local: "CEJA",
  },
  {
    data: "2025-11-27",
    hora: "13:20",
    jogo: "CETI X LUCIA ROCHA",
    modalidade: "Futsal Masculino Sub 17",
    ordem: "jogo 137",
    local: "CEJA",
  },
  {
    data: "2025-11-27",
    hora: "14:00",
    jogo: "MANOEL RAMOS X CEJA",
    modalidade: "Baleado Masculino Sub 15",
    ordem: "jogo 138",
    local: "CEJA",
  },
  {
    data: "2025-11-27",
    hora: "14:40",
    jogo: "CONVENIADA X CEBN",
    modalidade: "Baleado Feminino Sub 15",
    ordem: "jogo 139",
    local: "CEJA",
  },
  {
    data: "2025-11-27",
    hora: "15:20",
    jogo: "CEBC X CEJA",
    modalidade: "Baleado Feminino Sub 15",
    ordem: "jogo 140",
    local: "CEJA",
  },
  {
    data: "2025-11-27",
    hora: "16:00",
    jogo: "CEBC X CEJA",
    modalidade: "Baleado Masculino Sub 17",
    ordem: "jogo 141",
    local: "CEJA",
  },

  // JOGOS DE QUINTA FEIRA 27/11/2025 - QUADRA: CAFEZAL
  {
    data: "2025-11-27",
    hora: "08:40",
    jogo: "JOSÉ DIAS X CEJA",
    modalidade: "Handebol Masculino Sub 15",
    ordem: "jogo 142",
    local: "Cafezal",
  },
  {
    data: "2025-11-27",
    hora: "09:20",
    jogo: "JOSÉ DIAS X CEJA",
    modalidade: "Futsal Feminino Sub 11",
    ordem: "jogo 143",
    local: "Cafezal",
  },
  {
    data: "2025-11-27",
    hora: "10:00",
    jogo: "JOSÉ DIAS X CEJA",
    modalidade: "Futsal Masculino Sub 15",
    ordem: "jogo 144",
    local: "Cafezal",
  },
  {
    data: "2025-11-27",
    hora: "11:20",
    jogo: "CEBC X JOSÉ DIAS",
    modalidade: "Futsal Masculino Sub 13",
    ordem: "jogo 145",
    local: "Cafezal",
  },
  {
    data: "2025-11-27",
    hora: "12:00",
    jogo: "JOSÉ DIAS X CEBC",
    modalidade: "Baleado Feminino Sub 13",
    ordem: "jogo 146",
    local: "Cafezal",
  },

  // JOGOS DE QUINTA FEIRA 27/11/2025 - QUADRA: CETI
  {
    data: "2025-11-27",
    hora: "08:00",
    jogo: "ACM X FRANCISCO AMORIM",
    modalidade: "Futsal Masculino Sub 8",
    ordem: "jogo 147",
    local: "CETI",
  },
  {
    data: "2025-11-27",
    hora: "08:40",
    jogo: "MARLENE SANTANA X JOSÉ DIAS",
    modalidade: "Futsal Masculino Sub 9",
    ordem: "jogo 148",
    local: "CETI",
  },
  {
    data: "2025-11-27",
    hora: "09:20",
    jogo: "MARLENE SANTANA X ADELIETA RAMALHO",
    modalidade: "Futsal Masculino Sub 7",
    ordem: "jogo 149",
    local: "CETI",
  },
  {
    data: "2025-11-27",
    hora: "10:00",
    jogo: "FRANCISCO AMORIM X MARLENE SANTANA",
    modalidade: "Handebol Masculino Sub 9",
    ordem: "jogo 150",
    local: "CETI",
  },
  {
    data: "2025-11-27",
    hora: "10:40",
    jogo: "MARLENE SANTANA X FRANCISCO AMORIM",
    modalidade: "Handebol Feminino Sub 9",
    ordem: "jogo 151",
    local: "CETI",
  },
  {
    data: "2025-11-27",
    hora: "13:20",
    jogo: "ACM X ADELIETA RTAMALHO",
    modalidade: "Handebol Feminino Sub 9",
    ordem: "jogo 152",
    local: "CETI",
  },
  {
    data: "2025-11-27",
    hora: "14:00",
    jogo: "ADELIETA RTAMALHO X TEODULO LEITE",
    modalidade: "Baleado Masculino Sub 8",
    ordem: "jogo 153",
    local: "CETI",
  },
  {
    data: "2025-11-27",
    hora: "14:40",
    jogo: "MARLENE SANTANA X ACM",
    modalidade: "Baleado Masculino Sub 8",
    ordem: "jogo 154",
    local: "CETI",
  },
  {
    data: "2025-11-27",
    hora: "15:20",
    jogo: "FRANCISCO AMORIM X ACM",
    modalidade: "Handebol Feminino Sub 9",
    ordem: "jogo 155",
    local: "CETI",
  },

  // JOGOS DE QUINTA FEIRA 27/11/2025 - SOCIETY: ARENA SOCIAL
  {
    data: "2025-11-27",
    hora: "08:40",
    jogo: "CONVENIADA X CEJA",
    modalidade: "SOCIETY Masculino Sub 13",
    ordem: "jogo 156",
    local: "Arena Social",
  },
  {
    data: "2025-11-27",
    hora: "09:20",
    jogo: "CEBC X CONVENIADA",
    modalidade: "SOCIETY Masculino Sub 15",
    ordem: "jogo 157",
    local: "Arena Social",
  },
  {
    data: "2025-11-27",
    hora: "10:00",
    jogo: "CEBC X JOSENILDO LEITE",
    modalidade: "SOCIETY Masculino Sub 17",
    ordem: "jogo 158",
    local: "Arena Social",
  },
  {
    data: "2025-11-27",
    hora: "10:40",
    jogo: "CETI X CEBN",
    modalidade: "SOCIETY Masculino Sub 17",
    ordem: "jogo 159",
    local: "Arena Social",
  },
  {
    data: "2025-11-27",
    hora: "14:00",
    jogo: "CEJA X CEBC",
    modalidade: "SOCIETY Masculino Sub 13",
    ordem: "jogo 160",
    local: "Arena Social",
  },
  {
    data: "2025-11-27",
    hora: "14:40",
    jogo: "CONVENIADA X CEJA",
    modalidade: "SOCIETY Masculino Sub 15",
    ordem: "jogo 161",
    local: "Arena Social",
  },
  {
    data: "2025-11-27",
    hora: "15:20",
    jogo: "JOSENILDO LEITE X VITORIA LIMA",
    modalidade: "SOCIETY Masculino Sub 17",
    ordem: "jogo 162",
    local: "Arena Social",
  },
  {
    data: "2025-11-27",
    hora: "16:00",
    jogo: "CEJA X CETI",
    modalidade: "SOCIETY Masculino Sub 17",
    ordem: "jogo 163",
    local: "Arena Social",
  },

  // JOGOS DE SEXTA-FEIRA 28/11/2025 - QUADRA: GINÁSIO DE ESPORTES
  {
    data: "2025-11-28",
    hora: "08:00",
    jogo: "VITORIA LIMA X CETI",
    modalidade: "Futsal Feminino Sub 17",
    ordem: "jogo 164",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-28",
    hora: "08:40",
    jogo: "CEBC X CEJA",
    modalidade: "Futsal Feminino Sub 17",
    ordem: "jogo 165",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-28",
    hora: "09:20",
    jogo: "VITORIA LIMA X JOSENILDO LEITE",
    modalidade: "Futsal Masculino Sub 17",
    ordem: "jogo 166",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-28",
    hora: "10:00",
    jogo: "MARLENE SANTANA X CEJA",
    modalidade: "Futsal Feminino Sub 11",
    ordem: "jogo 167",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-28",
    hora: "10:40",
    jogo: "CETI X CEBC",
    modalidade: "Baleado Masculino Sub 17",
    ordem: "jogo 168",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-28",
    hora: "11:20",
    jogo: "CONVENIADA X CEBN",
    modalidade: "Handebol Masculino Sub 13",
    ordem: "jogo 169",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-28",
    hora: "12:00",
    jogo: "ACM X MARLENE SANTANA",
    modalidade: "Handebol Masculino Sub 9",
    ordem: "jogo 170",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-28",
    hora: "12:40",
    jogo: "ADELIETA RAMALHO X FRANCISCO AMORIM",
    modalidade: "Handebol Feminino Sub 9",
    ordem: "jogo 171",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-28",
    hora: "13:20",
    jogo: "LUCIA ROCHA X VITORIA LIMA",
    modalidade: "Volei Misto Aberto",
    ordem: "jogo 172",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-28",
    hora: "14:00",
    jogo: "CEBN X LUCIA ROCHA",
    modalidade: "Volei Masculino Sub 17",
    ordem: "jogo 173",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-28",
    hora: "14:40",
    jogo: "CEBC X VITORIA LIMA",
    modalidade: "Volei Feminino Sub 17",
    ordem: "jogo 174",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-28",
    hora: "15:20",
    jogo: "CONVENIADA X CEJA",
    modalidade: "Basquete Feminino Sub 13",
    ordem: "jogo 175",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-28",
    hora: "16:00",
    jogo: "CEJA X CETI",
    modalidade: "Basquete Masculino Sub 17",
    ordem: "jogo 176",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-28",
    hora: "16:40",
    jogo: "CEJA X CEBC",
    modalidade: "Basquete Masculino Sub 15",
    ordem: "jogo 177",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-28",
    hora: "17:20",
    jogo: "CEJA X CETI",
    modalidade: "Basquete Masculino Aberto",
    ordem: "jogo 178",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-28",
    hora: "18:00",
    jogo: "VITORIA LIMA X CEBC",
    modalidade: "Futsal Feminino Aberto",
    ordem: "jogo 179",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-28",
    hora: "18:40",
    jogo: "LUCIA ROCHA X CEBC",
    modalidade: "Futsal Masculino Sub 17",
    ordem: "jogo 180",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-28",
    hora: "19:20",
    jogo: "VITORIA LIMA X MANOEL RAMOS",
    modalidade: "Futsal Masculino Aberto",
    ordem: "jogo 181",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-28",
    hora: "20:00",
    jogo: "CETI X LUCIA ROCHA",
    modalidade: "Futsal Feminino Aberto",
    ordem: "jogo 182",
    local: "Ginásio de Esportes",
  },
  {
    data: "2025-11-28",
    hora: "20:40",
    jogo: "CETI X CEBC",
    modalidade: "Futsal Masculino Aberto",
    ordem: "jogo 183",
    local: "Ginásio de Esportes",
  },

  // JOGOS DE SEXTA-FEIRA 28/11/2025 - QUADRA: ADELIETA RAMALHO
  {
    data: "2025-11-28",
    hora: "08:00",
    jogo: "CETI X CEBC",
    modalidade: "Volei Feminino Sub 17",
    ordem: "jogo 184",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-28",
    hora: "08:40",
    jogo: "JOSENILDO LEITE X CEJA",
    modalidade: "Volei Masculino Sub 15",
    ordem: "jogo 185",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-28",
    hora: "09:20",
    jogo: "CETI X CEBC",
    modalidade: "Volei Misto Aberto",
    ordem: "jogo 186",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-28",
    hora: "10:00",
    jogo: "PORTAL DO SABER X JOSE DIAS",
    modalidade: "Baleado Feminino Sub 11",
    ordem: "jogo 187",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-28",
    hora: "10:40",
    jogo: "FRANCISCO AMORIM X MARLENE SANTANA",
    modalidade: "Baleado Masculino Sub 8",
    ordem: "jogo 188",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-28",
    hora: "11:00",
    jogo: "ADELIETA RAMALHO X MARIA DA GLORIA",
    modalidade: "Baleado Masculino Sub 9",
    ordem: "jogo 189",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-28",
    hora: "11:20",
    jogo: "CEBC X CONVENIADA",
    modalidade: "Baleado Masculino Sub 13",
    ordem: "jogo 190",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-28",
    hora: "12:00",
    jogo: "JOSE DIAS X MANOEL RAMOS",
    modalidade: "Baleado Masculino Sub 11",
    ordem: "jogo 191",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-28",
    hora: "12:40",
    jogo: "FRANCISCO AMORIM X ADELIETA RAMALHO",
    modalidade: "Baleado Feminino Sub 11",
    ordem: "jogo 192",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-28",
    hora: "13:20",
    jogo: "CEBN X CEJA",
    modalidade: "Baleado Masculino Sub 13",
    ordem: "jogo 193",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-28",
    hora: "14:00",
    jogo: "FRANCISCO AMORIM X PORTAL DO SABER",
    modalidade: "Baleado Feminino Sub 9",
    ordem: "jogo 194",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-28",
    hora: "14:40",
    jogo: "JOSENILDO LEITE X MARLENE SANTANA",
    modalidade: "Futsal Masculino Sub 11",
    ordem: "jogo 195",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-28",
    hora: "15:20",
    jogo: "MANOEL RAMOS X ADELIETA RAMALHO",
    modalidade: "Baleado Masculino Sub 13",
    ordem: "jogo 196",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-28",
    hora: "16:00",
    jogo: "JOSE DIAS X ADELIETA RAMALHO",
    modalidade: "Baleado Masculino Sub 11",
    ordem: "jogo 197",
    local: "Adelieta Ramalho",
  },
  {
    data: "2025-11-28",
    hora: "16:40",
    jogo: "FRANCISCO AMORIM X JOSENILDO LEITE",
    modalidade: "Baleado Feminino Sub 11",
    ordem: "jogo 198",
    local: "Adelieta Ramalho",
  },

  // JOGOS DE SEXTA-FEIRA 28/11/2025 - QUADRA: MARIA DA GLÓRIA
  {
    data: "2025-11-28",
    hora: "08:00",
    jogo: "CEBC X CEJA",
    modalidade: "Handebol Masculino Sub 13",
    ordem: "jogo 199",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-28",
    hora: "08:40",
    jogo: "MARIA DA GLORIA X FRANCISCO AMORIM",
    modalidade: "Handebol Masculino Sub 11",
    ordem: "jogo 200",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-28",
    hora: "09:20",
    jogo: "MARIA DA GLORIA X ADELIETA RAMALHO",
    modalidade: "Handebol Feminino Sub 11",
    ordem: "jogo 201",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-28",
    hora: "10:00",
    jogo: "EMILIANO ZAPATA X CEJA",
    modalidade: "Futsal Masculino Sub 13",
    ordem: "jogo 202",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-28",
    hora: "10:40",
    jogo: "CEJA X JOSE DIAS",
    modalidade: "Futsal Feminino Sub 13",
    ordem: "jogo 203",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-28",
    hora: "11:20",
    jogo: "CEBN X JOSENILDO LEITE",
    modalidade: "Futsal Masculino Sub 13",
    ordem: "jogo 204",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-28",
    hora: "12:00",
    jogo: "FRANCISCO AMORIM X CONVENIADA",
    modalidade: "Futsal Masculino Sub 13",
    ordem: "jogo 205",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-28",
    hora: "12:40",
    jogo: "CEBC X CEJA",
    modalidade: "Handebol Feminino Sub 13",
    ordem: "jogo 206",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-28",
    hora: "13:20",
    jogo: "JOSÉ DIAS X CEBC",
    modalidade: "Baleado Feminino Sub 13",
    ordem: "jogo 207",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-28",
    hora: "14:00",
    jogo: "CEBN X CEJA",
    modalidade: "Baleado Feminino Sub 13",
    ordem: "jogo 208",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-28",
    hora: "14:40",
    jogo: "ADELIETA RAMALHO X MARLENE SANTANA",
    modalidade: "Handebol Feminino Sub 11",
    ordem: "jogo 209",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-28",
    hora: "15:20",
    jogo: "ADELIETA RAMALHO X MARIA DA GLORIA",
    modalidade: "Baleado Feminino Sub 11",
    ordem: "jogo 210",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-28",
    hora: "16:00",
    jogo: "CEBC X MANOEL RAMOS",
    modalidade: "Baleado Masculino Sub 15",
    ordem: "jogo 211",
    local: "Maria da Glória",
  },
  {
    data: "2025-11-28",
    hora: "16:40",
    jogo: "CEBC X CEJA",
    modalidade: "Baleado Feminino Sub 17",
    ordem: "jogo 212",
    local: "Maria da Glória",
  },

  // JOGOS DE SEXTA FEIRA 28/11/2025 - QUADRA: CEJA
  {
    data: "2025-11-28",
    hora: "08:00",
    jogo: "JOSENILDO LEITE X JOSÉ DIAS",
    modalidade: "Futsal Masculino Sub 15",
    ordem: "jogo 213",
    local: "CEJA",
  },
  {
    data: "2025-11-28",
    hora: "08:40",
    jogo: "EMILIANOI ZAPATA X CEBN",
    modalidade: "Futsal Masculino Sub 15",
    ordem: "jogo 214",
    local: "CEJA",
  },
  {
    data: "2025-11-28",
    hora: "09:20",
    jogo: "CEBC X CONVENIADA",
    modalidade: "Futsal Masculino Sub 15",
    ordem: "jogo 215",
    local: "CEJA",
  },
  {
    data: "2025-11-28",
    hora: "10:00",
    jogo: "CONVENIADA X CEBN",
    modalidade: "Baleado Masculino Sub 15",
    ordem: "jogo 216",
    local: "CEJA",
  },
  {
    data: "2025-11-28",
    hora: "10:40",
    jogo: "CEBC X CEJA",
    modalidade: "Baleado Masculino Sub 15",
    ordem: "jogo 217",
    local: "CEJA",
  },
  {
    data: "2025-11-28",
    hora: "11:20",
    jogo: "CEJA X CEBN",
    modalidade: "Baleado Feminino Sub 15",
    ordem: "jogo 218",
    local: "CEJA",
  },
  {
    data: "2025-11-28",
    hora: "12:00",
    jogo: "CEBN X CONVENIADA",
    modalidade: "Futsal Feminino Sub 13",
    ordem: "jogo 219",
    local: "CEJA",
  },
  {
    data: "2025-11-28",
    hora: "12:40",
    jogo: "EMILIANO ZAPATA X CEBC",
    modalidade: "Futsal Masculino Sub 15",
    ordem: "jogo 220",
    local: "CEJA",
  },
  {
    data: "2025-11-28",
    hora: "13:20",
    jogo: "JOSÉ DIAS X CEBN",
    modalidade: "Futsal Feminino Sub 15",
    ordem: "jogo 221",
    local: "CEJA",
  },
  {
    data: "2025-11-28",
    hora: "14:00",
    jogo: "EMILIANO ZAPATA X CEBC",
    modalidade: "Futsal Feminino Sub 15",
    ordem: "jogo 222",
    local: "CEJA",
  },
  {
    data: "2025-11-28",
    hora: "14:40",
    jogo: "CEBN X CONVENIADA",
    modalidade: "Futsal Masculino Sub 15",
    ordem: "jogo 223",
    local: "CEJA",
  },
  {
    data: "2025-11-28",
    hora: "15:20",
    jogo: "CEJA X JOSENILDO LEITE",
    modalidade: "Futsal Masculino Sub 15",
    ordem: "jogo 224",
    local: "CEJA",
  },
  {
    data: "2025-11-28",
    hora: "16:00",
    jogo: "CEJA X CEBC",
    modalidade: "Handebol Feminino Sub 15",
    ordem: "jogo 225",
    local: "CEJA",
  },

  // JOGOS DE SEXTA FEIRA 28/11/2025 - SOCIETY: CETI
  {
    data: "2025-11-28",
    hora: "08:00",
    jogo: "VITORIA LIMA X CEBC",
    modalidade: "Society Masculino Sub 17",
    ordem: "jogo 226",
    local: "CETI (Society)",
  },
  {
    data: "2025-11-28",
    hora: "09:00",
    jogo: "CEBN X CEJA",
    modalidade: "Society Masculino Sub 17",
    ordem: "jogo 227",
    local: "CETI (Society)",
  },
  {
    data: "2025-11-28",
    hora: "10:00",
    jogo: "CEJA X CEBC",
    modalidade: "Society Masculino Sub 15",
    ordem: "jogo 228",
    local: "CETI (Society)",
  },
  {
    data: "2025-11-28",
    hora: "11:00",
    jogo: "CEBC X CONVENIADA",
    modalidade: "Society Masculino Sub 13",
    ordem: "jogo 229",
    local: "CETI (Society)",
  },

  // JOGOS DE SEXTA FEIRA 28/11/2025 - QUADRA: CETI
  {
    data: "2025-11-28",
    hora: "08:00",
    jogo: "PORTAL DO SABER X MARLENE SANTANA",
    modalidade: "Futsal Masculino Sub 8",
    ordem: "jogo 230",
    local: "CETI",
  },
  {
    data: "2025-11-28",
    hora: "09:20",
    jogo: "PORTAL DO SABER X ACM",
    modalidade: "Futsal Masculino Sub 7",
    ordem: "jogo 231",
    local: "CETI",
  },
  {
    data: "2025-11-28",
    hora: "10:00",
    jogo: "JOSÉ DIAS X MARLENE SANTANA",
    modalidade: "Futsal Masculino Sub 7",
    ordem: "jogo 232",
    local: "CETI",
  },
  {
    data: "2025-11-28",
    hora: "10:40",
    jogo: "JOSE DIAS X TEODULO LEITE",
    modalidade: "Futsal Masculino Sub 8",
    ordem: "jogo 233",
    local: "CETI",
  },
  {
    data: "2025-11-28",
    hora: "14:40",
    jogo: "ADELIETA X ACM",
    modalidade: "Futsal Masculino Sub 8",
    ordem: "jogo 234",
    local: "CETI",
  },
  {
    data: "2025-11-28",
    hora: "16:00",
    jogo: "TEODULO LEITE X MARLENE SANTANA",
    modalidade: "Futsal Masculino Sub 8",
    ordem: "jogo 235",
    local: "CETI",
  },
  {
    data: "2025-11-28",
    hora: "16:40",
    jogo: "ADELIETA RTAMALHO X EMILIANO ZAPATA",
    modalidade: "Futsal Masculino Sub 9",
    ordem: "jogo 236",
    local: "CETI",
  },
  {
    data: "2025-11-28",
    hora: "17:20",
    jogo: "CEJA X CETI",
    modalidade: "Basquete Masculino Aberto",
    ordem: "jogo 237",
    local: "Ginásio de Esportes",
  },
];
